name: CMake

on:
  push:
    branches:
      - master
      - conan

env:
  BUILD_TYPE: Release

jobs:
  Linux:
    name: Survive
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
            submodules: recursive

      - name: Install compiler
        run: |
          sudo apt-get install g++-10

      - name: Update packages
        run : |
          sudo apt-get update

      - name: Install conan
        run : |
          sudo pip install conan

      - name : Set conan profile
        run : |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name : Install libgl
        run : |
          sudo apt-get install libgl-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Build executable
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          conan install .. --settings compiler="gcc"
          cmake -D CMAKE_CXX_COMPILER=g++-10 .. -D CONAN_DISABLE_CHECK_COMPILER=ON
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: ${{github.workspace}}/build

  Windows:
    name: Survive
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install conan
        run: |
          pip install conan

      - name: Build executable
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          conan install ..
          cmake .. -G "Visual Studio 16" -D CONAN_DISABLE_CHECK_COMPILER=ON
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: ${{github.workspace}}/build