name: CMake

on:
  push:
    branches:
      - master
      - conan

env:
  BUILD_TYPE: Release

jobs:
  Linux:
    name: Survive
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
            submodules: recursive

      - name: Install compiler
        run: |
          sudo apt-get install g++-10

      - name: Update packages
        run : |
          sudo apt-get update

      - name: Install conan
        run : |
          sudo pip install conan

      - name: Set conan default profile
        run : |
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build executable
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          conan install ..
          cmake -D CMAKE_CXX_COMPILER=g++-10 ..
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: ${{github.workspace}}/build